### PR TITLE
docs: add summary to group endpoints for openapi docs📝

### PR DESCRIPTION
**Pull request by shivamvijaywargi**

### CODE REVIEW

**Review by sub1120 — COMMENTED** [review]
@shivamvijaywargi @NiteshSoma after seeing this PR, i have one doubt - Do we have a route which will return users of a particular group, because in frontend users adding screen, we have to hide users which are already part of that group so this validatation will not fail. If possible we can return users details in GET `/api/v1/group/:id​` itself.

**Comment by NiteshSoma** [comment]
> @shivamvijaywargi @NiteshSoma after seeing this PR, i have one doubt - Do we have a route which will return users of a particular group, because in frontend users adding screen, we have to hide users which are already part of that group so this validatation will not fail. If possible we can return users details in GET `/api/v1/group/:id​` itself.

@sub1120 I am actually working on that issue where we get back user details in getGroupById

**Comment by sub1120** [comment]
> > @shivamvijaywargi @NiteshSoma after seeing this PR, i have one doubt - Do we have a route which will return users of a particular group, because in frontend users adding screen, we have to hide users which are already part of that group so this validatation will not fail. If possible we can return users details in GET `/api/v1/group/:id​` itself.
> 
> @sub1120 I am actually working on that issue where we get back user details in getGroupById

Ooh nice. 

> > @shivamvijaywargi @NiteshSoma after seeing this PR, i have one doubt - Do we have a route which will return users of a particular group, because in frontend users adding screen, we have to hide users which are already part of that group so this validatation will not fail. If possible we can return users details in GET `/api/v1/group/:id​` itself.
> 
> @sub1120 I am actually working on that issue where we get back user details in getGroupById

Oh Nice! Then we are good.

**Review by sub1120 — APPROVED** [review]
Looks good to me.

**Pull request merged**
